### ISSUE TITLE
Migrations for tutor-richie post-upgrade

### ISSUE THREAD

**Issue by sion42x** [overhangio/tutor-richie#2]
@sampaccoud from Richie asked me to post this issue here, from: https://github.com/openfun/richie/issues/1548

It's particularly important because I may well be going about this all wrong; while trying to solve other issues I upgraded Richie to 2.9.1 from 2.8.2 (the tutor-richie default), and mistakenly updated a MySQL table attempting to fix an issue. I have rectified that by [making/running migrations manually](https://github.com/openfun/richie/issues/1548#issuecomment-997501854) which resolved the issue but created further questions. 

I believe overall there's just some confusion between tutor/richie in how the plugin is set up, it would be good to get an understanding for continued support by the Richie team (particularly with the CSRF, Category, and Migration issues I've unconvered).

**Comment by regisb** [comment]
Let's continue here the conversation that you started with @sampaccoud. 

https://github.com/openfun/richie/issues/1548#issuecomment-997501854:
> The tutor-richie Dockerfile does run makemigrations and migrate

https://github.com/openfun/richie/issues/1548#issuecomment-997752090:
> Running migrations in the Dockerfile is a bad idea imo.

Indeed, running migrations at build-time is a bad idea, and this is _not_ what is being done in Tutor. Here is the Dockerfile: https://github.com/overhangio/tutor-richie/blob/master/tutorrichie/templates/richie/build/richie/Dockerfile
Migrations are applied at runtime, during the "init" phase.

> I would strongly recommand not running Richie in Tutor. The preferred way to run Richie is classic Django as demonstrated in https://github.com/openfun/richie-site-factory. The Tutor plugin should take care of the openedx side. Both applications can be connected by configuration.

I am not quite sure that I understand correctly. You mean that Richie should be installed as a Django [reusable app](https://docs.djangoproject.com/en/4.0/intro/reusable-apps/) on top of the Open edX LMS, and not run as a Django project? But I thought that Richie was able to connect to other non-Python apps, such as Moodle? In these cases, Richie must be run as a standalone project, right? Which issues would it resolve if we ran Richie as a reusable app on top of the LMS?

@sion42x it is difficult for me to troubleshoot you further, as I am not aware of the changes that you made to your database. If you manually upgraded Richie from 2.8.2 to 2.9.1 then basically you removed the warranty label from the plugin :-/

**Comment by sion42x** [comment]
> Let's continue here the conversation that you started with @sampaccoud.
> 
> [openfun/richie#1548 (comment)](https://github.com/openfun/richie/issues/1548#issuecomment-997501854):
> 
> > The tutor-richie Dockerfile does run makemigrations and migrate
> 
> [openfun/richie#1548 (comment)](https://github.com/openfun/richie/issues/1548#issuecomment-997752090):
> 
> > Running migrations in the Dockerfile is a bad idea imo.
> 
> Indeed, running migrations at build-time is a bad idea, and this is _not_ what is being done in Tutor. Here is the Dockerfile: https://github.com/overhangio/tutor-richie/blob/master/tutorrichie/templates/richie/build/richie/Dockerfile Migrations are applied at runtime, during the "init" phase.
> 
> > I would strongly recommand not running Richie in Tutor. The preferred way to run Richie is classic Django as demonstrated in https://github.com/openfun/richie-site-factory. The Tutor plugin should take care of the openedx side. Both applications can be connected by configuration.
> 
> I am not quite sure that I understand correctly. You mean that Richie should be installed as a Django [reusable app](https://docs.djangoproject.com/en/4.0/intro/reusable-apps/) on top of the Open edX LMS, and not run as a Django project? But I thought that Richie was able to connect to other non-Python apps, such as Moodle? In these cases, Richie must be run as a standalone project, right? Which issues would it resolve if we ran Richie as a reusable app on top of the LMS?
> 
> @sion42x it is difficult for me to troubleshoot you further, as I am not aware of the changes that you made to your database. If you manually upgraded Richie from 2.8.2 to 2.9.1 then basically you removed the warranty label from the plugin :-/

I've reverted to a clean build and upgraded tutor-richie and tutor to Maple. I was able to get the migrations to run with a standard build (not modified in any way). I believe my confusion was with order of operations with custom richie builds vs. quickstart runs.

**Comment by sampaccoud** [comment]
> You mean that Richie should be installed as a Django [reusable app](https://docs.djangoproject.com/en/4.0/intro/reusable-apps/) on top of the Open edX LMS, and not run as a Django project? But I thought that Richie was able to connect to other non-Python apps, such as Moodle? In these cases, Richie must be run as a standalone project, right? Which issues would it resolve if we ran Richie as a reusable app on top of the LMS?

I meant running it as a reusable app in a separate Django project, not in a Django project started by Tutor.
My understanding is that Tutor is an implementation of OpenEdX so I find it confusing that it also integrates the Django project for Richie as a separate app. It makes it hard to customize it as we can see here with @sion42x's confusion?

Said differently, I think we don't need Tutor to run Richie because Richie is designed as a third party app for DjangoCMS which, unlike OpenEdX can be run in production like any Django project.

**Comment by regisb** [comment]
> I believe my confusion was with order of operations with custom richie builds vs. quickstart runs.

OK so I'll close this issue @sion42x.

> Said differently, I think we don't need Tutor to run Richie because Richie is designed as a third party app for DjangoCMS which, unlike OpenEdX can be run in production like any Django project.

Right. Usually, in Tutor plugins, apps are packaged in such a way that users have to perform very few (if any) manual steps in order to integrate with their Open edX platform. For instance, in the [tutor-minio](https://github.com/overhangio/tutor-minio) plugin, MinIO is run as a Docker container out of the box. In general, it's fairly easy to run an app as a standalone service -- it's usually just a matter of running a single `docker run` command. What's complicated is the interaction of the app with the rest of the platform. For instance, the tutor-richie plugin handles the following:

- Load balancing and SSL termination (https://github.com/overhangio/tutor-richie/blob/master/tutorrichie/patches/caddyfile)
- Replica scaling on Kubernetes (https://github.com/overhangio/tutor-richie/blob/master/tutorrichie/patches/k8s-deployments)
- Connection to the mysql and elasticsearch servers shared with the rest of the Open edX platform, running optionally outside of the cluster (https://github.com/overhangio/tutor-richie/blob/master/tutorrichie/templates/richie/apps/env.d/production)
- Initialisation and bootstrapping of Richie (https://github.com/overhangio/tutor-richie/blob/master/tutorrichie/templates/richie/hooks/richie/init)
etc.

If we decide to remove the richie service from the plugin, then all of this operational knowledge needs to be documented, and users need to gain some expertise at managing Richie. 

I understand the need for end users to customise their Richie service: running a fork, running on top of another Django project,  etc. This is possible with Tutor (and relatively easy). For instance, users can decide to build a custom Docker image that bundles Richie. Then, modify the `RICHIE_DOCKER_IMAGE` setting in Tutor to make use of that image. They get the best of both worlds: full customization and easy container orchestration/configuration.

We can further improve the customizability of the tutor-richie plugin by making it extendable. This is very easy to achieve with the introduction of `{{ patch(...) }}` statements in the tutor-richie templates.

Alternatively, we can introduce a new `RICHIE_RUN_FRONTEND` setting, which would default to `true`; when it is set to false then we would not be running the Richie frontend at all in Tutor. We should simply acknowledge that running Richie separately is a fairly complex endeavor, for all the reasons listed above. I would not be in favour of this solution, because I think that this is not what users expect of Tutor -- and here I'm thinking not just of single-server users, but also of large, state-managed Open edX platforms.
